PRAGMA foreign_keys = ON;

ALTER TABLE media ADD COLUMN web_byte_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN thumb_byte_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN poster_byte_size INTEGER NOT NULL DEFAULT 0;
